---
abstract: 'Typographically enhance HTML trees'
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Embellish
requires:
  HTML::Tree: 3.21
  perl: 5.8.0
resources:
  repository: http://github.com/madsen/html-embellish
version: 0.03
